USE [master]
GO

/****** Object:  Database [BPKB]    Script Date: 13/12/2024 16:23:57 ******/
CREATE DATABASE [BPKB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BPKB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BPKB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BPKB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BPKB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BPKB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BPKB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BPKB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BPKB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BPKB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BPKB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BPKB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BPKB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BPKB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BPKB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BPKB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BPKB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BPKB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BPKB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BPKB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BPKB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BPKB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BPKB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BPKB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BPKB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BPKB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BPKB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BPKB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BPKB] SET RECOVERY FULL 
GO

ALTER DATABASE [BPKB] SET  MULTI_USER 
GO

ALTER DATABASE [BPKB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BPKB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BPKB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BPKB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BPKB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BPKB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BPKB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BPKB] SET  READ_WRITE 
GO

